[package]
name = "normalized-hasher"
version = "0.2.0-SNAPSHOT"
authors = ["Florian Gamböck <mail@floga.de>"]
edition = "2021"

description = "Create cross-platform hashes of text files."
repository = "https://github.com/FloGa/normalized-hasher"
readme = "README.md"
categories = ["algorithms", "command-line-utilities"]
keywords = ["cli", "hash", "newline"]
license = "MIT"
include = ["src/main.rs", "LICENSE", "README.md"]

[dependencies]
base16ct = { version = "0.2.0", features = ["alloc"] }
clap = { version = "4.1.4", features = ["derive"] }
sha2 = "0.10.6"

[dev-dependencies]
tempfile = "3.7.0"
